version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 15
    assignees:
      - 'Lalit2005'
    reviewers:
      - 'Lalit2005'
